language: python
python:
    - "2.7"
    - "pypy"
install:
    - "pip install -e ."
    - "pip install -r requirements.txt"
    - "pip install coveralls"
script:
    - "coverage run ./run_tests.py --with-coverage"
after_success:
  - "coveralls"
