language: python
python:
    - "2.7"
install:
    - "pip install -e ."
    - "pip install -r requirements.txt"
    - "pip install coveralls"
    - "pip install flake8"
before_script:
    - "flake8 savory_pie"
script:
    - "./run_tests.py --with-coverage"
after_success:
    - "coveralls"
